### ISSUE TITLE
Unable to run app in browser

### ISSUE THREAD

**Issue by mcL86** [angular-redux/example-app#7] opened 2017-02-07 11:14 UTC
Hi,

i was looking forward to take a look at your example-app.

Webpack is able to build and "serve" the app on localhost.
![webpack](https://cloud.githubusercontent.com/assets/11556505/22688963/d15f17d6-ed2e-11e6-939b-eed93bd4752d.png)

But opening http://localhost:4200 results in an empty page.

![chrome_error](https://cloud.githubusercontent.com/assets/11556505/22688962/d15c1c66-ed2e-11e6-9e4a-4ab5a97c157f.png)

Steps executed:

1. git clone https://github.com/angular-redux/example-app.git
2. npm install
3. ng serve

Maybe i missed something....

regards,
marcel

**Comment by SethDavenport** [comment] 2017-02-07 13:59
Hi Marcel,

Seems to be working for me.  Can you tell me the following pieces of information:
* what version of node are you running? (`node -v`)
* what version of the angular CLI are you running? (`ng -v`)
* your screenshot looks like Chrome - is that right or is it actually a different browser?

**Comment by mcL86** [comment] 2017-02-07 16:34
Hi Seth,

`ng -v

angular-cli: 1.0.0-beta.26
node: 6.9.4
os: linux x64
`

Yes, this is the console from chrome.

**Comment by mattmoussa** [comment] 2017-02-08 12:13
Hi @SethDavenport ,

I had the same error message, following the same steps as @mcL86 . I used the following versions:

- @angular/cli: 1.0.0-beta.30
- node: 7.5.0
- os: win32 x64
- browser: Chrome 56.0.2924.87 (64-bit)

It seemed to be an issue in the app.component.ts constructor.

**Comment by SethDavenport** [comment] 2017-02-10 17:10
Reproduced.

This happens when you don't have the redux Chrome extension installed, which explains why I wasn't seeing it initially. It has been fixed by PR #11, which I merged yesterday evening.

Please pull new code and try again.

**Comment by SethDavenport** [comment] 2017-02-10 17:12
Feel free to reopen if this is still an issue.

**Closed by SethDavenport** 2017-02-10 17:12 UTC

**Comment by mcL86** [comment] 2017-02-13 08:24
Hi @SethDavenport ,

thank you for your help.

After the installation of the Redux DevTools everything works fine.

Which part of the code do i have to remove to run this without the Redux DevTools?

**Comment by SethDavenport** [comment] 2017-02-13 12:46
The code has been updated to make the devtools not necessary. This is the commit that does it: https://github.com/angular-redux/example-app/commit/9aab537c9238a7d8118dc244bc72937f2def357d
