### ISSUE TITLE
Installed this and it throws an error on page load

### ISSUE THREAD

**Issue by willphdavies** [angular-redux/example-app#10] opened 2017-02-08 21:10 UTC
TypeError: Cannot read property 'apply' of null
    at http://localhost:4200/vendor.bundle.js:69832:12
    at NgRedux.configureStore (http://localhost:4200/vendor.bundle.js:26065:131)
    at new AppComponent (http://localhost:4200/main.bundle.js:547:17)
    at new Wrapper_AppComponent (/AppModule/AppComponent/wrapper.ngfactory.js:7:18)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.createInternal (/AppModule/AppComponent/host.ngfactory.js:15:28)
    at CompiledTemplate.proxyViewClass.AppView.createHostView (http://localhost:4200/vendor.bundle.js:83463:21)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:83919:52)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:44603:25)
    at ApplicationRef_.bootstrap (http://localhost:4200/vendor.bundle.js:42537:57)
    at http://localhost:4200/vendor.bundle.js:42356:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://localhost:4200/vendor.bundle.js:42356:42)
    at http://localhost:4200/vendor.bundle.js:42308:27
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:105172:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:31928:37)

**Comment by todzhang** [comment] 2017-02-10 01:56
I met the same error. My enviroment is 
f:\temp\angular\example-app>node --version
v6.9.4

f:\temp\angular\example-app>npm --version
3.10.8

on windows 8.1

**Comment by SethDavenport** [comment] 2017-02-10 04:08
Looks like the same issue as #7. I couldn't repro the other day but I may be using an older version of the angular CLI. I've set aside some time to look into it tomorrow.

**Comment by SethDavenport** [comment] 2017-02-10 17:10
Reproduced.

This happens when you don't have the redux Chrome extension installed, which explains why I wasn't seeing it initially. It has been fixed by PR #11, which I merged yesterday evening.

Please pull new code and try again.

**Closed** 2017-02-10 17:13 UTC
